questions.append("How do astronauts eat in space?")
    answers.append(["They eat from special pouches (correct)", "They eat normally", "They eat from special plates, "They do not eat"])
    correct_answers.append("a")
questions.append("Which country invented gunpowder?")
    answers.append(["They eat from special pouches (correct)", "They eat normally", "They eat from special plates, "They do not eat"])
    correct_answers.append("a")
questions.append("Which 2 colors make hot pink dough in baking?")
    answers.append(["They eat from special pouches (correct)", "They eat normally", "They eat from special plates, "They do not eat"])
    correct_answers.append("a")
